version: '3.8'

services:
  # Main web application
  web:
    build: .
    container_name: uttaranchal-university
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=8080
    volumes:
      # Mount logs for debugging (optional)
      - ./logs:/var/log/nginx
    networks:
      - university-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.university.rule=Host(`university.localhost`)"
      - "traefik.http.services.university.loadbalancer.server.port=8080"

  # Development server with hot reload (optional)
  dev:
    image: nginx:alpine
    container_name: uttaranchal-university-dev
    ports:
      - "3000:80"
    volumes:
      - .:/usr/share/nginx/html:ro
      - ./nginx-dev.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    networks:
      - university-network
    profiles:
      - dev
    command: ["nginx", "-g", "daemon off;"]

  # Optional: Simple file server for development
  file-server:
    image: python:3.11-alpine
    container_name: university-file-server
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app
    command: ["python", "-m", "http.server", "8000"]
    networks:
      - university-network
    profiles:
      - dev

networks:
  university-network:
    driver: bridge

volumes:
  logs:
    driver: local